### ISSUE TITLE
 generate_labels.py:data_path

### ISSUE THREAD

**Issue by XDpaddle** [oufuzhao/CLIB-FIQA#2]
when I run the generate_labels.py,what should I write in data_path = './'?Could you give me a link for the dataset you use?

**Comment by oufuzhao** [comment]
Hi, thank you for your attention.

'data_path' is the path of the dataset. However, due to some usage restrictions, I may not be able to give you the download link to share the dataset here, I hope you can understand~ In the following, I would like to give you some instructions regarding the 'data_path':

For example, if 'data_path' is /root/dataset/, the format might be
/root/dataset
| -- /root/dataset/ID1#,
| --  | -- /root/dataset/ID1#/Image1#.jpg,
| --  | -- /root/dataset/ID1#/Image#2.jpg, 
...
| -- /root/dataset/ID#100,
| --  | -- /root/dataset/ID#100/Image#1.jpg.
| --  | --  ...
| --  | -- /root/dataset/ID#100/Image#95.jpg. 

where, the ID# and Image# are the ID subfile and image code name respectively, and they can be any subfolder or image name.

I hope the above cases can help you understand.
